"""sdsd

Revision ID: 8606ad4b998b
Revises: f0b45c6a6104
Create Date: 2024-10-10 16:22:31.164492

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8606ad4b998b'
down_revision = 'f0b45c6a6104'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('survey', schema=None) as batch_op:
        batch_op.alter_column('field1',
               existing_type=sa.FLOAT(),
               nullable=True)
        batch_op.alter_column('comment1',
               existing_type=sa.VARCHAR(length=140),
               nullable=True)
        batch_op.alter_column('field2',
               existing_type=sa.FLOAT(),
               nullable=True)
        batch_op.alter_column('comment2',
               existing_type=sa.VARCHAR(length=140),
               nullable=True)
        batch_op.alter_column('field3',
               existing_type=sa.FLOAT(),
               nullable=True)
        batch_op.alter_column('comment3',
               existing_type=sa.VARCHAR(length=140),
               nullable=True)
        batch_op.alter_column('field4',
               existing_type=sa.FLOAT(),
               nullable=True)
        batch_op.alter_column('comment4',
               existing_type=sa.VARCHAR(length=140),
               nullable=True)
        batch_op.alter_column('field5',
               existing_type=sa.FLOAT(),
               nullable=True)
        batch_op.alter_column('comment5',
               existing_type=sa.VARCHAR(length=140),
               nullable=True)
        batch_op.alter_column('field6',
               existing_type=sa.FLOAT(),
               nullable=True)
        batch_op.alter_column('comment6',
               existing_type=sa.VARCHAR(length=140),
               nullable=True)
        batch_op.alter_column('field7',
               existing_type=sa.FLOAT(),
               nullable=True)
        batch_op.alter_column('comment7',
               existing_type=sa.VARCHAR(length=140),
               nullable=True)
        batch_op.alter_column('field8',
               existing_type=sa.FLOAT(),
               nullable=True)
        batch_op.alter_column('comment8',
               existing_type=sa.VARCHAR(length=140),
               nullable=True)
        batch_op.alter_column('field9',
               existing_type=sa.FLOAT(),
               nullable=True)
        batch_op.alter_column('comment9',
               existing_type=sa.VARCHAR(length=140),
               nullable=True)
        batch_op.alter_column('field10',
               existing_type=sa.FLOAT(),
               nullable=True)
        batch_op.alter_column('comment10',
               existing_type=sa.VARCHAR(length=140),
               nullable=True)
        batch_op.alter_column('field11',
               existing_type=sa.FLOAT(),
               nullable=True)
        batch_op.alter_column('field12',
               existing_type=sa.FLOAT(),
               nullable=True)
        batch_op.alter_column('comment12',
               existing_type=sa.VARCHAR(length=140),
               nullable=True)
        batch_op.alter_column('field13',
               existing_type=sa.FLOAT(),
               nullable=True)
        batch_op.alter_column('comment13',
               existing_type=sa.VARCHAR(length=140),
               nullable=True)
        batch_op.alter_column('field14',
               existing_type=sa.FLOAT(),
               nullable=True)
        batch_op.alter_column('comment14',
               existing_type=sa.VARCHAR(length=140),
               nullable=True)
        batch_op.alter_column('field15',
               existing_type=sa.FLOAT(),
               nullable=True)
        batch_op.alter_column('comment15',
               existing_type=sa.VARCHAR(length=140),
               nullable=True)
        batch_op.alter_column('field16',
               existing_type=sa.FLOAT(),
               nullable=True)
        batch_op.alter_column('comment16',
               existing_type=sa.VARCHAR(length=140),
               nullable=True)
        batch_op.alter_column('field17',
               existing_type=sa.FLOAT(),
               nullable=True)
        batch_op.alter_column('comment17',
               existing_type=sa.VARCHAR(length=140),
               nullable=True)
        batch_op.alter_column('field18',
               existing_type=sa.FLOAT(),
               nullable=True)
        batch_op.alter_column('comment18',
               existing_type=sa.VARCHAR(length=140),
               nullable=True)
        batch_op.alter_column('field19',
               existing_type=sa.FLOAT(),
               nullable=True)
        batch_op.alter_column('comment19',
               existing_type=sa.VARCHAR(length=140),
               nullable=True)
        batch_op.alter_column('result',
               existing_type=sa.FLOAT(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('survey', schema=None) as batch_op:
        batch_op.alter_column('result',
               existing_type=sa.FLOAT(),
               nullable=False)
        batch_op.alter_column('comment19',
               existing_type=sa.VARCHAR(length=140),
               nullable=False)
        batch_op.alter_column('field19',
               existing_type=sa.FLOAT(),
               nullable=False)
        batch_op.alter_column('comment18',
               existing_type=sa.VARCHAR(length=140),
               nullable=False)
        batch_op.alter_column('field18',
               existing_type=sa.FLOAT(),
               nullable=False)
        batch_op.alter_column('comment17',
               existing_type=sa.VARCHAR(length=140),
               nullable=False)
        batch_op.alter_column('field17',
               existing_type=sa.FLOAT(),
               nullable=False)
        batch_op.alter_column('comment16',
               existing_type=sa.VARCHAR(length=140),
               nullable=False)
        batch_op.alter_column('field16',
               existing_type=sa.FLOAT(),
               nullable=False)
        batch_op.alter_column('comment15',
               existing_type=sa.VARCHAR(length=140),
               nullable=False)
        batch_op.alter_column('field15',
               existing_type=sa.FLOAT(),
               nullable=False)
        batch_op.alter_column('comment14',
               existing_type=sa.VARCHAR(length=140),
               nullable=False)
        batch_op.alter_column('field14',
               existing_type=sa.FLOAT(),
               nullable=False)
        batch_op.alter_column('comment13',
               existing_type=sa.VARCHAR(length=140),
               nullable=False)
        batch_op.alter_column('field13',
               existing_type=sa.FLOAT(),
               nullable=False)
        batch_op.alter_column('comment12',
               existing_type=sa.VARCHAR(length=140),
               nullable=False)
        batch_op.alter_column('field12',
               existing_type=sa.FLOAT(),
               nullable=False)
        batch_op.alter_column('field11',
               existing_type=sa.FLOAT(),
               nullable=False)
        batch_op.alter_column('comment10',
               existing_type=sa.VARCHAR(length=140),
               nullable=False)
        batch_op.alter_column('field10',
               existing_type=sa.FLOAT(),
               nullable=False)
        batch_op.alter_column('comment9',
               existing_type=sa.VARCHAR(length=140),
               nullable=False)
        batch_op.alter_column('field9',
               existing_type=sa.FLOAT(),
               nullable=False)
        batch_op.alter_column('comment8',
               existing_type=sa.VARCHAR(length=140),
               nullable=False)
        batch_op.alter_column('field8',
               existing_type=sa.FLOAT(),
               nullable=False)
        batch_op.alter_column('comment7',
               existing_type=sa.VARCHAR(length=140),
               nullable=False)
        batch_op.alter_column('field7',
               existing_type=sa.FLOAT(),
               nullable=False)
        batch_op.alter_column('comment6',
               existing_type=sa.VARCHAR(length=140),
               nullable=False)
        batch_op.alter_column('field6',
               existing_type=sa.FLOAT(),
               nullable=False)
        batch_op.alter_column('comment5',
               existing_type=sa.VARCHAR(length=140),
               nullable=False)
        batch_op.alter_column('field5',
               existing_type=sa.FLOAT(),
               nullable=False)
        batch_op.alter_column('comment4',
               existing_type=sa.VARCHAR(length=140),
               nullable=False)
        batch_op.alter_column('field4',
               existing_type=sa.FLOAT(),
               nullable=False)
        batch_op.alter_column('comment3',
               existing_type=sa.VARCHAR(length=140),
               nullable=False)
        batch_op.alter_column('field3',
               existing_type=sa.FLOAT(),
               nullable=False)
        batch_op.alter_column('comment2',
               existing_type=sa.VARCHAR(length=140),
               nullable=False)
        batch_op.alter_column('field2',
               existing_type=sa.FLOAT(),
               nullable=False)
        batch_op.alter_column('comment1',
               existing_type=sa.VARCHAR(length=140),
               nullable=False)
        batch_op.alter_column('field1',
               existing_type=sa.FLOAT(),
               nullable=False)

    # ### end Alembic commands ###
