"""sdsd

Revision ID: f0b45c6a6104
Revises: 
Create Date: 2024-10-10 15:22:56.743557

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f0b45c6a6104'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=True),
    sa.Column('about_me', sa.String(length=140), nullable=True),
    sa.Column('last_seen', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_user_username'), ['username'], unique=True)

    op.create_table('followers',
    sa.Column('follower_id', sa.Integer(), nullable=False),
    sa.Column('followed_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['followed_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('follower_id', 'followed_id')
    )
    op.create_table('post',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('body', sa.String(length=140), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_post_timestamp'), ['timestamp'], unique=False)
        batch_op.create_index(batch_op.f('ix_post_user_id'), ['user_id'], unique=False)

    op.create_table('survey',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('survey_name', sa.String(length=140), nullable=False),
    sa.Column('field1', sa.Float(), nullable=False),
    sa.Column('comment1', sa.String(length=140), nullable=False),
    sa.Column('field2', sa.Float(), nullable=False),
    sa.Column('comment2', sa.String(length=140), nullable=False),
    sa.Column('field3', sa.Float(), nullable=False),
    sa.Column('comment3', sa.String(length=140), nullable=False),
    sa.Column('field4', sa.Float(), nullable=False),
    sa.Column('comment4', sa.String(length=140), nullable=False),
    sa.Column('field5', sa.Float(), nullable=False),
    sa.Column('comment5', sa.String(length=140), nullable=False),
    sa.Column('field6', sa.Float(), nullable=False),
    sa.Column('comment6', sa.String(length=140), nullable=False),
    sa.Column('field7', sa.Float(), nullable=False),
    sa.Column('comment7', sa.String(length=140), nullable=False),
    sa.Column('field8', sa.Float(), nullable=False),
    sa.Column('comment8', sa.String(length=140), nullable=False),
    sa.Column('field9', sa.Float(), nullable=False),
    sa.Column('comment9', sa.String(length=140), nullable=False),
    sa.Column('field10', sa.Float(), nullable=False),
    sa.Column('comment10', sa.String(length=140), nullable=False),
    sa.Column('field11', sa.Float(), nullable=False),
    sa.Column('field12', sa.Float(), nullable=False),
    sa.Column('comment12', sa.String(length=140), nullable=False),
    sa.Column('field13', sa.Float(), nullable=False),
    sa.Column('comment13', sa.String(length=140), nullable=False),
    sa.Column('field14', sa.Float(), nullable=False),
    sa.Column('comment14', sa.String(length=140), nullable=False),
    sa.Column('field15', sa.Float(), nullable=False),
    sa.Column('comment15', sa.String(length=140), nullable=False),
    sa.Column('field16', sa.Float(), nullable=False),
    sa.Column('comment16', sa.String(length=140), nullable=False),
    sa.Column('field17', sa.Float(), nullable=False),
    sa.Column('comment17', sa.String(length=140), nullable=False),
    sa.Column('field18', sa.Float(), nullable=False),
    sa.Column('comment18', sa.String(length=140), nullable=False),
    sa.Column('field19', sa.Float(), nullable=False),
    sa.Column('comment19', sa.String(length=140), nullable=False),
    sa.Column('result', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('survey', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_survey_timestamp'), ['timestamp'], unique=False)
        batch_op.create_index(batch_op.f('ix_survey_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('survey', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_survey_user_id'))
        batch_op.drop_index(batch_op.f('ix_survey_timestamp'))

    op.drop_table('survey')
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_post_user_id'))
        batch_op.drop_index(batch_op.f('ix_post_timestamp'))

    op.drop_table('post')
    op.drop_table('followers')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_username'))
        batch_op.drop_index(batch_op.f('ix_user_email'))

    op.drop_table('user')
    # ### end Alembic commands ###
